/**
 * 物品图标映射配置
 * 用于在数据定义中提供图标路径
 */

const { ICON_PATHS } = require('../config/resourcePaths')

// 药水图标映射
const POTION_ICON_MAP = {
  'hp': ICON_PATHS.POTION.HP,
  'mp': ICON_PATHS.POTION.MP,
  'dual': ICON_PATHS.POTION.DUAL
}

// 装备槽位图标映射
const SLOT_ICONS = {
  'weapon': ICON_PATHS.WEAPON.DEFAULT,
  'helmet': ICON_PATHS.EQUIPMENT.HELMET,
  'armor': ICON_PATHS.EQUIPMENT.ARMOR_CHEST,
  'shield': ICON_PATHS.EQUIPMENT.SHIELD,
  'belt': ICON_PATHS.EQUIPMENT.BELT,
  'cloak': ICON_PATHS.EQUIPMENT.CLOAK,
  'necklace': ICON_PATHS.EQUIPMENT.NECKLACE,
  'ring': ICON_PATHS.EQUIPMENT.RING,
  'bracer': ICON_PATHS.EQUIPMENT.BRACER,
  'amulet': ICON_PATHS.EQUIPMENT.AMULET,
  'gem': ICON_PATHS.EQUIPMENT.GEM,
  'earring': ICON_PATHS.EQUIPMENT.EARRING,
  'mount': ICON_PATHS.EQUIPMENT.MOUNT
}

// 默认图标
const DEFAULT_ITEM_ICON = ICON_PATHS.EQUIPMENT.DEFAULT
const DEFAULT_POTION_ICON = ICON_PATHS.POTION.DEFAULT

module.exports = {
  POTION_ICON_MAP,
  SLOT_ICONS,
  DEFAULT_ITEM_ICON,
  DEFAULT_POTION_ICON
}